name: print-name

on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Name
        run: echo "Hello, this is a GitHub Action!"
